name: smart_refrigerator
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  provider: ^5.0.0
  google_sign_in: ^4.5.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.5
  firebase_storage: ^8.0.6
  animated_theme_switcher: ^2.0.1-nullsafety.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  google_place: ^0.4.0
  flutter_dotenv: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
